// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrdacbfrfwddxmllbuuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZGFjYmZyZndkZHhtbGxidXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTA5OTAsImV4cCI6MjA2NDA4Njk5MH0.cjGDCeDrSdKBjK0DFnStLehEKSOLzbAFrztgRg-YtDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);